server:
  port: 2010
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  application:
    name: property-management-system
  datasource:
    url: jdbc:mysql://localhost:3306/rb_pms?useUnicode=true&characterEncoding=UTF-8&connectionCollation=utf8mb4_unicode_ci&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

app:
  project-name: 物业管理系统
  cors-origins: http://localhost:4010,http://localhost:3010,http://127.0.0.1:4010,http://127.0.0.1:3010
  upload-dir: ${user.dir}/data/uploads
